set_property SRC_FILE_INFO {cfile:G:/fpga/0708/0810/xdma/xdma/xdma.srcs/constrs_1/new/PCIE_REST.xdc rfile:../../../xdma.srcs/constrs_1/new/PCIE_REST.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:G:/fpga/0708/0810/xdma/xdma/xdma.srcs/constrs_1/new/ps2_pins.xdc rfile:../../../xdma.srcs/constrs_1/new/ps2_pins.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U9 [get_ports {ref_clk_clk_p[0]}]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y8 [get_ports {pcie_mgt_rxn[0]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R4 [get_ports rst_n]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B7 [get_ports ps2_clk]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B6 [get_ports ps2_data]
